### ISSUE TITLE
Error loading images in mitometer

### ISSUE THREAD

**Issue by sarabitar** [aelefebv/Mitometer#10]
Hi!

I am trying to use the mitometer app to analysze some data but I am unable to load images into the app. 
I have the needed Add-ons already. 
I open the app, select 2D, insert my pixel size and time, then select my TIFF image and I always get the following error:

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 769 (0x301) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 771 (0x303) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 20752 (0x5110) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 20753 (0x5111) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 20754 (0x5112) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 769 (0x301) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 771 (0x303) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 20752 (0x5110) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 20753 (0x5111) encountered.'

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 20754 (0x5112) encountered.'

Unable to perform assignment because the size of the left side is 1080-by-1080 and the size of the right side is

1080-by-1080-by-4.

 

Error in openTifs (line 57)

                importedImage{i}(:,:,frameNum) = uint8(255 * mat2gray(tifIm.read()));

 

Error in GUI2/Start2DButtonPushed (line 1029)

                [ImAllTemp,~,fileNameTemp,app.path] = openTifs(); %open all selected images

Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 427)

Error while evaluating Button PrivateButtonPushedFcn.

I used it a couple of months ago and it worked fine. Would you be able to help me troubleshoot?

**Comment by aelefebv** [comment]
Hello!
I see.. It looks like your image could possibly have been converted weirdly, considering all the TIFF library warnings.
If possible, try to open it in FIJI/ImageJ, and save the file as a tiff through there.
If that doesn't work, I can try to take a look at your file as well.

Austin

**Comment by njk18** [comment]
Hello,

I tried debugging the problem with @sarabitar and we overcame the first problem. The TIFF images were 32bit color, so we avoided the path that was throwing an error by converting the images to 8bit, this got them to load, however, we couldn't get any further. 

`        for frameNum = 1:numFrames{i}
            tifIm.setDirectory(frameNum);
            if imInfo(1).BitDepth ~= 8
                importedImage{i}(:,:,frameNum) = uint8(255 * mat2gray(tifIm.read()));
            else
                importedImage{i}(:,:,frameNum) = tifIm.read();
            end
        end
`

Segmentation, tracking, and analysis weren't generating any data or graphs.
Are there any specific properties the TIFF images should have to visualize fission and fusion evens?

**Comment by aelefebv** [comment]
Strange, it should automatically convert to 8bit for the background removal process.
If it worked well in a previous version, you can always use an old version while I try to figure out the issue: https://github.com/aelefebv/Mitometer/commits/main

It would be helpful to have some example files so I can try to debug
