### ISSUE TITLE
Error when running on MATLAB 2021a

### ISSUE THREAD

**Issue by pywugate** [aelefebv/Mitometer#4]
Hello Austin,

I tested many files 512x512x5x927, 461x479x1x927, or 512x512x1x927. 
I also tested choosing single file in start2D or start3D, and choosing multiple files in start3D. 
This error occured after "testing the parameter" process.
During tracking frame, it stopped at "tracking frame 3 of 927".

Error using  : 
For colon operator with char operands, first and last operands must be char.

Error in prctile

Error in quantile (line 59)
y = prctile(x,100.*p,varargin{:});

Error in trackMitochondria (line 207)
        startCost = quantile(runningConfidentCosts,0.98,'all');

Error in GUI/Start2DButtonPushed (line 833)
                    trackPrelim =
                    trackMitochondria(Im,ImOG,weightsPrelim,app.micronPerPixel,app.secondsPerFrame,app.distThreshMicrons,useframeThreshSeconds,0,1); 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

(Then I tried it on 2020b, it overcame somehow to frame 33 of 927 but not finished yet.)

**Comment by aelefebv** [comment]
Sounds like maybe the toolboxes mentioned in the read me need to be installed:
"Statistics and Machine Learning Toolbox"(https://www.mathworks.com/help/stats/)

"Image Processing Toolbox" (https://www.mathworks.com/help/images/)

let me know if that works!

**Comment by pywugate** [comment]
Those 2 toolboxs are installed in either 2021a or 2020b.
Right now I can try on 2020b. 
You can leave the issue and reconsider this issue if other users also struggle this problem.
Thanks!

**Comment by aelefebv** [comment]
Hmm, interesting. Okay, well thank you for the info!
I will keep looking into it and try to understand what's happening.

**Comment by aelefebv** [comment]
Hello, I am closing this thread. Please open a new one if the issue persists or you have any other problems.
