### ISSUE TITLE
 Analysis tab empty when running on MATLAB 2021a

### ISSUE THREAD

**Issue by vaibhavbcm** [aelefebv/Mitometer#5]
Hi Austin, 

I don't see any error while using the package and the segmentation works really well on the different 2D and 3D images I have used. But the analysis tab is always empty after the processing. Please have a look at the screenshot. 

I am using airyscan images, 1024X1024,  Z=3, axial distance=0.186um. 

Thanks 
Vaibhav 

![MITOMETR_ERROR_2](https://user-images.githubusercontent.com/19628797/131534924-fdbe00de-deb7-4145-adc3-bc54dac1b99c.png)
![MITOMETR_ERROR_3](https://user-images.githubusercontent.com/19628797/131534932-74452046-8147-49a8-9174-752533045ddd.png)
![MITOMETR_ERROR](https://user-images.githubusercontent.com/19628797/131535317-4b9a7eb1-ace1-40d4-a29c-d643907b91fa.png)

**Comment by aelefebv** [comment]
Hi Vaibhav,

Ooo, nice images!
The manual provided with the software runs through this analysis tab quite thoroughly, but here’s a brief version:
Press the “Create group” button at the bottom right (even if it’s only one image).
Select your group from the drop down at the top right.
Select the parameters you want to analyze.
Press “Add to graph”

You should then be able to visualize and save any parameters you want.

Let me know if that solved your problem!

Austin

**Comment by vaibhavbcm** [comment]
Hi Austin, 

It solved the issue, thanks for your help. 

Vaibhav
