### ISSUE TITLE
Can't load images into matlab

### ISSUE THREAD

**Issue by Melphala** [aelefebv/Mitometer#7]
Hello Austin,

thanks for this great tool. I have problems loading images into the Mitometer App.
My Matlab version is R2021a and I installed Statistics and Machine Learning Toolbox and Image Processing Toolbox.
I also have the imageJ Matlab script (https://imagej.net/scripting/matlab)

Here is the output of the command window:

log4j:WARN No appenders could be found for logger (loci.formats.ClassList).
log4j:WARN Please initialize the log4j system properly.

Error using catdirs (line 25)
All arguments must be character vectors.

Error in addpath (line 64)
p = catdirs(mfilename, varargin{1:n});

Error in openIJ (line 8)
    addpath(path);

Error in GUI2/OpenFIJIButtonPushed (line 2702)
            openIJ()
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

Unrecognized function or variable 'track'.

Error in trackMitochondria (line 266)
[mitoDynamics,~] = getDynamics(micronPerPixel,secondsPerFrame,track);

Error in GUI2/Start2DButtonPushed (line 1132)
                    trackPrelim =
                    trackMitochondria(Im,ImOG,weightsPrelim,app.micronPerPixel,app.secondsPerFrame,app.distThreshMicrons,useframeThreshSeconds,0,1);

Error in GUI2/IJButtonPushed (line 2719)
            Start2DButtonPushed(app, event)
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

Kind regards,
Johannes

**Comment by aelefebv** [comment]
Hi Johannes,
Sorry the hear about the issue!
Can you tell me a little bit more about when this error occurs (i.e. what button you pressed, what kind of image you loaded, was it through the ImageJ module, etc.). As in-depth as possible would be the most helpful to help me solve this!
Austin

**Comment by Melphala** [comment]
Yes, I open the Mitometer App; Press the Open ImageJ Button; I select the scripts folder of Fiji; Fiji opens after a while; I open 9 test images in Fiji; I press the IJ Button next to 2D; I set pixel size and frame rate; Mitometer starts to process 147 frames, but its really slow. After several hours the 147 frames are processed and I get the Errors I posted.

Maybe this two errors are most important, since they occur before trying to load the images:
log4j:WARN No appenders could be found for logger (loci.formats.ClassList).
log4j:WARN Please initialize the log4j system properly.

**Comment by aelefebv** [comment]
Hmm.. interesting. Any chance you can send me the file that isn’t working? I can try to debug it on my end.

**Comment by Melphala** [comment]
Hi,

I tried a few things again. I can't load images into the mitometer app through imagej, but it works with the 'Start 2D' button.
Segmentation works for single images, but not for timelaps tif stacks. That is the only thing not working right now.

Kind regards,
Johannes
