### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by bbrenner2** [aelefebv/Mitometer#8]
I wonder if you might have any example tiff images you could provide

**Comment by bbrenner2** [comment]
When I try to run my own data in MatLab 2021b I get the following error message:

> Array indices must be positive integers or logical values.
> 
> Error in optimizeSigmaThresh (line 108)
> threshOptimal = threshMatrix(floor(median(rowMin)));
> 
> Error in GUI2/Start3DButtonPushed (line 1301)
>                     [app.sig,app.thr,costs] = optimizeSigmaThresh(ImBgRemoved(:,:,:,find(meanInt==max(meanInt))));
>  
> Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 427)
> Error while evaluating Button PrivateButtonPushedFcn.

I have attached the file in question (I get this error with all the files I try to run). It is just 1 3d image, and the pixel size is 0.35 and voxel size is 0.125. Tiffs are not supported so I converted it to a gif
![Confocal5_2](https://user-images.githubusercontent.com/92020098/136710811-c1b637d5-646d-4ab1-9299-fd52a098582d.gif)
.

**Comment by aelefebv** [comment]
Unfortunately you need a time lapse image for the program to properly perform segmentation, since it uses variability in mitochondrial number and area between frames to determine parameters for the Gaussian filter and threshold value.
