### ISSUE TITLE
Segmentation and tracking completed but the GUI did not have outputs

### ISSUE THREAD

**Issue by zichenzachwang** [aelefebv/Mitometer#9]
Hi Austin,

I am trying to run Mitometer with R2020b recently updated and two toolkit added. So I input the image as z,t,x,y with 49x5x171x332 for test purpose. Then the app started running and everything was progressing fine. 

![Capture](https://user-images.githubusercontent.com/72236294/145938308-08d13441-f6f5-4f01-8b17-a91a79de5469.PNG)

However after it's all complete without any matlab error message, the segmentation and tracking windows are empty without any result. I tried to click on the buttons but I also got error messages. I think it is trying to say somewhere the processing went wrong so the GUI broke.

![Capture2](https://user-images.githubusercontent.com/72236294/145938289-9f88d740-7c60-4ae5-9b5f-ef2acb58dced.PNG)

This is pretty bizarre to me. I wonder if you have any idea and thanks in advance!

Zach

**Comment by aelefebv** [comment]
Hi Zach,

Thanks for bringing this up!
You mention the windows are empty after segmentation and tracking are complete, did you select your file in the "Select file(s)" list, and press "Select highlighted", then wait until the files are done loading before trying to save the tif stack? I'm specifically referring to page 6 of the manual.

Thank you,
Austin

**Comment by zichenzachwang** [comment]
> Hi Zach,
> 
> Thanks for bringing this up! You mention the windows are empty after segmentation and tracking are complete, did you select your file in the "Select file(s)" list, and press "Select highlighted", then wait until the files are done loading before trying to save the tif stack? I'm specifically referring to page 6 of the manual.
> 
> Thank you, Austin

Indeed that was my mistake. Thank you!
